### ISSUE TITLE
PurityFb failing for versions invalid value

### ISSUE THREAD

**Issue by mgagliardo** [purestorage/purity_fb_python_client#15]
Hello there, so it seems there's a bug in the lib as I am trying to connect to my Pure Storage array with the purity_fb lib and i got the following:
```
>>> import urllib3
>>> import purity_fb
>>> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
>>>
>>> fb = PurityFb(MY_ARRAY_IP)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/purity_fb/fb_client.py", line 47, in __init__
    self._version = self._choose_rest_version()
  File "/usr/lib/python3.6/site-packages/purity_fb/fb_client.py", line 142, in _choose_rest_version
    versions = self.list_versions()
  File "/usr/lib/python3.6/site-packages/purity_fb/fb_client.py", line 74, in list_versions
    return self.api_version.list_versions().versions
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/version_api.py", line 64, in list_versions
    (data) = self.list_versions_with_http_info(**kwargs)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/version_api.py", line 133, in list_versions_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/api_client.py", line 164, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/api_client.py", line 242, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/api_client.py", line 282, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/api_client.py", line 634, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/models/version_response.py", line 48, in __init__
    self.versions = versions
  File "/usr/lib/python3.6/site-packages/purity_fb/api_client/models/version_response.py", line 71, in versions
    raise ValueError("Invalid value for `versions`, must not be `None`")
ValueError: Invalid value for `versions`, must not be `None`
```

purity_fb is latest `1.5.1` installed both over pipy and git, I can confirm the array works perfectly as I am hitting it with the `purestorage` OSS python lib and works smoothly.

**Comment by zhengl7** [comment]
From the stack trace looks like it's trying to call the array's REST API to get supported REST versions but got nothing instead. 

Can you try to hit this REST API on your browser `<your_array_hostname>/api/api_version` to see what returns?  It should return a JSON with supported versions like,
```json
{
versions: [
"1.0",
"1.1",
"1.2",
"1.3",
"1.4"
]
}
```

**Comment by zhengl7** [comment]
Actually did you not replace `MY_ARRAY_IP` in code with the actual IP address of the array?

**Comment by mgagliardo** [comment]
Yes, of course I replaced the IP with the actual.

`{"version": ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12", "1.13", "1.14", "1.15"]}`

Wait, this is for flash blade right? We have a Flash Array, not Blade.

I am closing this PR. Sorry to bother you.
