### ISSUE TITLE
zip_safe flag not set; analyring contents ...... value Error

### ISSUE THREAD

**Issue by Inlitha** [purestorage/purity_fb_python_client#38]
hello,
I installed your API to supervise the berries.\
But when I install it I have this error which must not be normal.\
```batch
zip_safe flag not set; analyzing archive contents...

Traceback (most recent call last):

  File "setup.py", line 43, in <module>

    """

  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run

    self.do_egg_install()

  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 93, in do_egg_install

    self.run_command('bdist_egg')

  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 232, in run

    os.path.join(archive_root,'EGG-INFO'), self.zip_safe()

  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 271, in zip_safe

    return analyze_egg(self.bdist_dir, self.stubs)

  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 407, in analyze_egg

    safe = scan_module(egg_dir, base, name, stubs) and safe

  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 438, in scan_module

    code = marshal.load(f); f.close()

ValueError: bad marshal data (unknown type code)
```
How do I solve this problem?\
is this error disabling to use the API?\

Thank you

**Comment by ychen-ps** [comment]
@Inlitha can you share how you installed `purity_fb`? I ran `pip install purity_fb` and this worked for me. Thanks!

**Comment by Inlitha** [comment]
I choose **Setuptools**  for install.

**Comment by ychen-ps** [comment]
I ran into the same problem when I ran Setuptools on my macOS. I followed the suggestions in this [link](https://github.com/timotheus/ebaysdk-python/issues/240) and it worked for me. However, please be very careful and do not just run one command to delete all .pyc files on your machine.

Otherwise, try using pip to install the sdk.

**Comment by ychen-ps** [comment]
@Inlitha I'm assuming that you have resolved this issue. Closing this for now. Feel free to reopen this if you're still encountering this issue.
